"""empty message

Revision ID: 6221c75b052d
Revises: 118650dc3607
Create Date: 2019-01-08 12:36:01.679912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6221c75b052d'
down_revision = '118650dc3607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('role', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user', 'role')
    # ### end Alembic commands ###
